version: '3'
services:
  app:
    build:
      context: ./docker/app
      args:
        DOCKER_UID: ${DOCKER_UID:-1000}
    environment:
      MYSQL_DATABASE: c9
      #MYSQL_USER: MYSQL_USER
      #MYSQL_PASSWORD: MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./html:/var/www/html
    ports:
      - 20980:80
  db:
    build: ./docker/db
    environment:
      MYSQL_DATABASE: c9
      #MYSQL_USER: MYSQL_USER
      #MYSQL_PASSWORD: MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - ./docker/db/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    ports:
      - 20981:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
  mailhog:
      image: "mailhog/mailhog:latest"
      ports:
          - "${FORWARD_MAILHOG_PORT:-1025}:1025"
          - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
  redis:
      image: "redis:alpine"
      ports:
          - "${FORWARD_REDIS_PORT:-6379}:6379"
      volumes:
          - "sailredis:/data"
volumes:
    # sailmysql:
    #     driver: local
    #    sailpostgresql:
    #        driver: local
    sailredis:
        driver: local