#! /usr/bin/sh

REPOSITORY_DIR_PATH=${PWD}
ENV_FILE_PATH=${REPOSITORY_DIR_PATH}/.env
LARAVEL_ENV_FILE_PATH=${REPOSITORY_DIR_PATH}/html/laravel/.env

PASSWORD=`pwmake --help`

echo MYSQL_ROOT_PASSWORD=\'${PASSWORD}\' >> ${ENV_FILE_PATH}
